### ISSUE TITLE
Suggestion for LED function

### ISSUE THREAD

**Issue by mano1979** [MrBuddyCasino/ESP32_Alexa#14]
There is only one neopixel needed for feedback. One blinking red and another blue is useless because neopixels ar RGB. This can be easily done with one neopixel. 

Also it would be nice to be able to select if i want to use the led function at all. Or change it to a sound notification. It would be great to have this option in the "menuconfig".

The led function seems to create a lot of distortion while recording my voice. Often it even prevents the setup from working correctly after a reboot. (only a loud ticking noise at about 3Hz, after pressing the button, while the serial terminal says ```[0;31mE (73502) led_ui: setColors 0=-2146288040, 1=1073546048[0m``` over and over again)

**Comment by MrBuddyCasino** [comment]
This means your power supply isn't great, maybe add a large cap. If you want a specific feature implemented, I'm afraid you'll have to do it yourself - thats why it is open source.
