### ISSUE TITLE
No laughter came out

### ISSUE THREAD

**Issue by LilyGO** [MrBuddyCasino/ESP32_Alexa#18]
hi. According to your instructions, I successfully uploaded the firmware, get the mac address input to the Amazon website, and get the authentication token. Then I typed into menuconfig. Of course, I also entered the WIFI account and password.
Second microphone model SPH0645LM4H, I2S codec model PCM9102A. (I also bought max98357A, but the module test did not succeed). Finally, I uploaded a few pictures here, I hope you can answer my doubts.
best wishes
![screenshot_3](https://user-images.githubusercontent.com/31160602/36766103-5a4e69fa-1c6f-11e8-9b88-2ad564e7fabb.png)

**Comment by MrBuddyCasino** [comment]
Startup sequence looks good, can't see a reason why it wouldn't work.
