### ISSUE TITLE
Alexa api authorization update!?!

### ISSUE THREAD

**Issue by mano1979** [MrBuddyCasino/ESP32_Alexa#20]
Today i received this email.(see below)
Does this have any consequences to ESP32-ALEXA code?

`[ACTION REQUIRED]Update certificate authorities for your AVS clientPosted On: March 14, 2018Alexa Developer:The Alexa Voice Service is moving to Amazon Trust Services (ATS) certificates for all AVS endpoints. Because of this change, all Alexa-enabled devices and applications must support certificates vended from ATS by June 15, 2018. Your device or application will not be able to connect to AVS if it does not support ATS certificates after June 15, 2018.We recommend testing that your device or mobile application successfully connects to AVS endpoints using ATS certificates. Please follow the instructions listed on the AVS Developer Forum to learn how to complete testing and upgrade support for ATS.`

**Comment by MrBuddyCasino** [comment]
Not 100% sure, but I think not.

**Comment by mano1979** [comment]
Ok. Thank you.
