### ISSUE TITLE
MAC address purpose

### ISSUE THREAD

**Issue by chegewara** [MrBuddyCasino/ESP32_Alexa#24]
Hi, what is the mac address purpose to generate token? I am generating token with random mac and it still working, my last tested mac was AA:AA:AA:AA:AA:AA.

**Comment by MrBuddyCasino** [comment]
Its just a handy way to associate a randomness with a specific hardware instance, which is what Amazon wants in this case.

**Comment by chegewara** [comment]
Yes, i figured it out its deviceID in amzon SDK. Thanks.
