### ISSUE TITLE
support for v1053 mp3 encoder

### ISSUE THREAD

**Issue by gyroing** [MrBuddyCasino/ESP32_Alexa#32]
i wonder,is it possible to add support to vs1053 mp encoder ?  like KaraDio32

**Comment by MrBuddyCasino** [comment]
Why would want that?

**Comment by gyroing** [comment]
for 2 purpose : 1- not having the Dac module and better quality  , as wll as  vs1053  has a licensed mp3 decoding.

**Comment by MrBuddyCasino** [comment]
Makes no sense to me.
1. I2S already provides full quality at a cheaper cost than the VS1053
2. MP3 decoders never have required a license
3. MP3 patents have all run out anyway

**Comment by gyroing** [comment]
Thanks for reply , and i forget vs1053 included internal mic also , so it is possible to combine audio (in-out),

**Comment by chegewara** [comment]
i can say that esp32 simple-alexa board designed by @kodera2t is working pretty awesome with this library and is not very expensive (around $26 or 29)
