### ISSUE TITLE
Make menuconfig

### ISSUE THREAD

**Issue by Dema323** [MrBuddyCasino/ESP32_Alexa#36]
Hi im running into some issues with the make menuconfig part. There is something i am missing but i can't figure out what. When i run the make menuconfig i receive the following error: 
```
Makefile:10: /path/to/esp-idf/make/project.mk: No such file or directory
make: *** No rule to make target '/path/to/esp-idf/make/project.mk'.  Stop.
```
I never used the esp tools before so im not so good with it.
Thank you for your time !

**Comment by chegewara** [comment]
Do you have setup IDF_PATH in your environment? Check it with `printenv IDF_PATH`.

**Comment by Dema323** [comment]
```
`maxim@DESKTOP-SBL495D MINGW32 ~/esp-idf/ESP32_Alexa
$ printenv IDF_PATH
/path/to/esp-idf

maxim@DESKTOP-SBL495D MINGW32 ~/esp-idf/ESP32_Alexa
$
`
```
this is the output i get

**Comment by chegewara** [comment]
`/path/to/esp-idf`
This needs to be real path to esp-idf folder on you system. Use:
`export IDF_PATH=...` where ... is real path. On windows it will be something like that:
`/c/msys32/home/maxim/esp-idf` where c is drive letter where you have your msys32 and i am assuming you have msys32 in top level folder.

**Comment by Dema323** [comment]
Right, i don't know how i missed that. I was copying without actually reading. Dumb mistake. Thank you for your time, im gonna try it now but i should be able to figure it out now. Thanks again !

**Comment by Dema323** [comment]
serial.serialutil.SerialException: could not open port 'C:/Users/maxim/Desktop/m                                                                                                                                  sys32/dev/ttyUSB5': WindowsError(2, 'The system cannot find the file specified.                                                                                                                                  ')

I seem to have some issues with the port, i need COM 5 and from what i understand it can't access it ? I also tried /dev/ttyUSB05 but no luck. Any ideas ?

**Comment by chegewara** [comment]
`make menuconfig` and change port in serial flasher config menu to com5.

**Comment by Dema323** [comment]
so /dev/ttyusbCOM5 ?

**Comment by chegewara** [comment]
its for linux, on windows you have to use only `com5`

**Comment by Dema323** [comment]
ah that explains my google search results. Thanks i will try it

**Comment by Dema323** [comment]
im sorry to keep bothering, but im getting the following error 

```
    raise SerialException("could not open port {!r}: {!r}".format(self.portstr, ctypes.WinError()))
serial.serialutil.SerialException: could not open port 'COM5': WindowsError(5, 'Access is denied.')
make: *** [/c/users/maxim/desktop/msys32/home/maxim/esp-idf/components/esptool_py/Makefile.projbuild:55: flash] Error 1
```

**Comment by Dema323** [comment]
im sorry my atom editor was holding the port open, when i closed it the port was open for the program to execute.
